
package PPFISM;

import java.util.Vector;
import javax.swing.JOptionPane;
import java.sql.*;


public class SelectAlgo extends javax.swing.JFrame {

    static double psi;
    
    public SelectAlgo() {
        initComponents();
        setTitle("Select an Algorithm");
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setLocationRelativeTo(null);
    }
   Vector<Vector> data=new Vector<Vector>();
    Vector colNames=new Vector(); 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Select Algorithm");
        setBackground(new java.awt.Color(153, 255, 153));
        setForeground(new java.awt.Color(153, 255, 153));

        jButton1.setFont(new java.awt.Font("Dodger", 0, 14)); // NOI18N
        jButton1.setText("Naive Algorithm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter the value of PSI:");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Enter the Psi value in the range of 0-1");

        jLabel3.setFont(new java.awt.Font("Backslash", 1, 24)); // NOI18N
        jLabel3.setText("Select Algorithm");

        jButton2.setFont(new java.awt.Font("Dodger", 0, 14)); // NOI18N
        jButton2.setText("MinFIA Algorithm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Dodger", 0, 14)); // NOI18N
        jButton3.setText("MaxFIA Algorithm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jButton3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jButton1))
                            .addComponent(jButton2))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the psi value in the range of 0-1");
        }
        psi = Double.parseDouble(jTextField1.getText());
        if(psi < 0 || psi > 1)
        {
            JOptionPane.showMessageDialog(null,"Please enter the psi value in the range of 0-1");
        }
        Naive nv = new Naive();
        nv.Test();
        
        JOptionPane.showMessageDialog(null,"Output is stored in NaiveOutput table");
        
        displayOutput("FinalItemSets");
        FinalFrequentItemSets display = new FinalFrequentItemSets();
        display.displayTable(data, colNames);
        display.setVisible(true);
        

           
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the psi value in the range of 0-1");
        }
        psi = Double.parseDouble(jTextField1.getText());
        if(psi < 0 || psi > 1)
        {
            JOptionPane.showMessageDialog(null,"Please enter the psi value in the range of 0-1");
        }
            MinFIA mf = new MinFIA();
            mf.Test();
            JOptionPane.showMessageDialog(null,"Output is stored in MinFIAOutput table");
            
            displayOutput("FinalItemSets");
        FinalFrequentItemSets display = new FinalFrequentItemSets();
        display.displayTable(data, colNames);
        display.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         if(jTextField1.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please enter the psi value in the range of 0-1");
        }
        psi = Double.parseDouble(jTextField1.getText());
        if(psi < 0 || psi > 1)
        {
            JOptionPane.showMessageDialog(null,"Please enter the psi value in the range of 0-1");
        }
            MaxFIA mf = new MaxFIA();
            mf.Test();
            JOptionPane.showMessageDialog(null,"Output is stored in MaxFIAOutput table");
            
            displayOutput("FinalItemSets");
        FinalFrequentItemSets display = new FinalFrequentItemSets();
        display.displayTable(data, colNames);
        display.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public void displayOutput(String input) //https://www.youtube.com/watch?v=GAl1FSKvoFY&t=765s
{
    
try
{
    String query="select * from "+input; 
                PreparedStatement stmt=MyDataBase.createStatement(query);
                ResultSet rs=stmt.executeQuery();             
                ResultSetMetaData rsmd=rs.getMetaData();
                int cols=rsmd.getColumnCount();                
                int i,k,e;   
                data.clear();
                colNames.clear();                
                for(int l=0;l<cols;l++)
                {
                       e=l+1;
                    colNames.add("Item"+e);
                }  
                
                k=0;
                while(rs.next())
                {
                     data.add(new Vector());
                    for(int j=1;j<cols+1;j++)
                    {
                        i=rs.getInt(j);
                        data.get(k).add(""+i);
                    }
                    k++;
                }  
               
                rs.close();
                stmt.close();
}
catch(Exception e)
{
    System.out.println("Error while displaying the Final frequent itemsets" +e);
}
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectAlgo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectAlgo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
